import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <div>
      <Head>
        <title>My Next.js VR Experience</title>
        <script src="https://aframe.io/releases/1.2.0/aframe.min.js" />
      </Head>
      <a-scene>
        <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9"/>
        <a-sphere position="0 1.25 -5" radius="1.25" color="#EF2D5E"/>
        <a-cylinder
          position="1 0.75 -3"
          radius="0.5" 
          height="1.5" 
          color="#FFC65D"
        />
        <a-plane
          position="0 0 -4"
          rotation="-90 0 0" 
          width="4" 
          height="4" 
          color="#7BC8A4" 
        />
        <a-sky color="#ECECEC" />
      </a-scene>
    </div>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
